# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-27 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t1', '0002_auto_20181124_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='phd_self',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t1.Year'),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t1.Year'),
        ),
        migrations.AddField(
            model_name='conference_journal',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t1.Year'),
        ),
        migrations.AddField(
            model_name='counsltancy',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t1.Year'),
        ),
        migrations.AddField(
            model_name='exclusive_research',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t1.Year'),
        ),
        migrations.AddField(
            model_name='fdp',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t1.Year'),
        ),
        migrations.AddField(
            model_name='funding',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t1.Year'),
        ),
        migrations.AddField(
            model_name='honours',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t1.Year'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t1.Year'),
        ),
        migrations.AddField(
            model_name='online_courses',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t1.Year'),
        ),
        migrations.AddField(
            model_name='open_courses',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t1.Year'),
        ),
        migrations.AddField(
            model_name='phd_guide',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t1.Year'),
        ),
        migrations.AddField(
            model_name='refreshers_course',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t1.Year'),
        ),
        migrations.AddField(
            model_name='sttp',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t1.Year'),
        ),
    ]
