# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-28 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1', '0004_auto_20181128_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdp',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
