# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-28 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1', '0006_auto_20181128_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exclusive_research',
            old_name='from_date',
            new_name='from_date_1',
        ),
        migrations.RenameField(
            model_name='exclusive_research',
            old_name='to_date',
            new_name='from_date_2',
        ),
        migrations.RenameField(
            model_name='exclusive_research',
            old_name='name_organization',
            new_name='name_organization_1',
        ),
        migrations.AddField(
            model_name='exclusive_research',
            name='from_date_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exclusive_research',
            name='name_organization_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exclusive_research',
            name='name_organization_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exclusive_research',
            name='to_date_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exclusive_research',
            name='to_date_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exclusive_research',
            name='to_date_3',
            field=models.DateField(blank=True, null=True),
        ),
    ]
